load("@io_bazel_rules_go//go:def.bzl", "go_test")

go_test(
    name = "logictest_test",
    srcs = [
        "logictest_test.go",
        "main_test.go",
    ],
    data = glob(["testdata/**"]),
    deps = [
        "//pkg/base",
        "//pkg/cql/cqlwire",
        "//pkg/cql/types",
        "//pkg/security/securityassets",
        "//pkg/security/securitytest",
        "//pkg/server",
        "//pkg/settings/cluster",
        "//pkg/testutils/datapathutils",
        "//pkg/testutils/serverutils",
        "//pkg/testutils/testcluster",
        "//pkg/util/leaktest",
        "//pkg/util/log",
        "@com_github_cockroachdb_datadriven//:datadriven",
        "@com_github_stretchr_testify//require",
    ],
)
