load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tdswire",
    srcs = [
        "login7.go",
        "packet.go",
        "prelogin.go",
        "token.go",
    ],
    importpath = "github.com/cockroachdb/cockroach/pkg/tds/tdswire",
    visibility = ["//visibility:public"],
)

go_test(
    name = "tdswire_test",
    srcs = [
        "packet_test.go",
        "token_test.go",
    ],
    embed = [":tdswire"],
)
