load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tds",
    srcs = [
        "auth.go",
        "conn.go",
        "server.go",
    ],
    importpath = "github.com/cockroachdb/cockroach/pkg/tds",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/tds/tdswire",
    ],
)

go_test(
    name = "tds_test",
    srcs = [
        "integration_test.go",
        "server_test.go",
    ],
    embed = [":tds"],
    deps = [
        "//pkg/tds/tdswire",
    ],
)
