load("@io_bazel_rules_go//go:def.bzl", "go_test")

go_test(
    name = "e2etest_test",
    srcs = [
        "bsqldb_test.go",
        "main_test.go",
        "pymssql_test.go",
    ],
    data = glob(["testdata/**"]),
    deps = [
        "//pkg/base",
        "//pkg/security/securityassets",
        "//pkg/security/securitytest",
        "//pkg/server",
        "//pkg/sql/isql",
        "//pkg/tds",
        "//pkg/testutils/serverutils",
        "//pkg/testutils/testcluster",
        "//pkg/util/leaktest",
        "//pkg/util/log",
        "@com_github_stretchr_testify//require",
    ],
)
