load("@io_bazel_rules_go//go:def.bzl", "go_test")

go_test(
    name = "smoketest_test",
    srcs = [
        "main_test.go",
    ],
    deps = [
        "//pkg/base",
        "//pkg/security/securityassets",
        "//pkg/security/securitytest",
        "//pkg/server",
        "//pkg/sql/isql",
        "//pkg/tds",
        "//pkg/tds/tdswire",
        "//pkg/testutils/serverutils",
        "//pkg/testutils/testcluster",
        "//pkg/util/leaktest",
        "//pkg/util/log",
    ],
)
