load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tnswire",
    srcs = [
        "data.go",
        "data_encoding.go",
        "doc.go",
        "encoding.go",
        "packet.go",
        "write_buffer.go",
    ],
    importpath = "github.com/cockroachdb/cockroach/pkg/tns/tnswire",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_cockroachdb_errors//:errors",
    ],
)

go_test(
    name = "tnswire_test",
    srcs = [
        "data_test.go",
        "packet_test.go",
    ],
    embed = [":tnswire"],
    deps = [
        "@com_github_stretchr_testify//require",
    ],
)
